# Generated by Django 2.2.8 on 2020-10-22 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201020_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='strip_charge_id',
            new_name='stripe_charge_id',
        ),
    ]
