# Generated by Django 2.2.8 on 2020-10-22 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_order_ref_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='countries',
            new_name='country',
        ),
    ]
