# Generated by Django 2.2.8 on 2020-10-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20201026_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='being_delievered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='recieved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_granted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_requested',
            field=models.BooleanField(default=False),
        ),
    ]
