# Generated by Django 2.2.8 on 2020-10-26 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20201026_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='being_delievered',
            new_name='being_delivered',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='recieved',
            new_name='received',
        ),
    ]
